# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  # Router service
  router:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # BCRA Agent
  bcra:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Comex Agent
  comex:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Senasa Agent
  senasa:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Auditor service
  auditor:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Frontend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://147.182.248.187:8001
        - VITE_BCRA_URL=http://147.182.248.187:8002
        - VITE_COMEX_URL=http://147.182.248.187:8003
        - VITE_SENASA_URL=http://147.182.248.187:8004
        - VITE_AUDITOR_URL=http://147.182.248.187:8005
    container_name: frontend
    ports:
      - "80:80"  # Use port 80 for production
    environment:
      - VITE_API_BASE_URL=http://147.182.248.187:8001
    networks:
      - oracle-network
    depends_on:
      - router
      - auditor
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M